#!/bin/sh
set -eu
DEFAULT_SERVER_URL="http://127.0.0.1:1338"
SERVER_URL="${CCP_SERVER_URL:-$DEFAULT_SERVER_URL}"
SERVER_URL="${SERVER_URL%/}"
export CCP_SERVER_URL="$SERVER_URL"
setup=$(mktemp)
trap 'rm -f "$setup"' EXIT HUP INT TERM
curl -fsSL "$SERVER_URL/setup-client.sh" -o "$setup"
sh "$setup"
